---
title: SpatialEpiLab Publications
output:
  html_document: 
    toc: true
    toc_float: true
---

<link rel="stylesheet" href="styles.css" type="text/css">

```{r, echo = FALSE, warning=FALSE, message=FALSE}
library(kableExtra)
library(knitr)
source('functions/scholar_allpubs.R')
source('./scholar_ids/scholar_ids.R')
all_pubs <- scholar_allpubs(scholar_ids)
```

<center>Here you can find an overview of our research publications. Please contact us ([our contact details are found here](contact.html){target="_blank"}) if you would like access to full texts of any of our work.</center>

<br>

## 2022
```{r, echo = FALSE, warning=FALSE, message=FALSE}
kable(data.frame(all_pubs %>%
          dplyr::filter(Year == 2022) %>%
            dplyr::select(-Year)), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```


## 2021
```{r, echo = FALSE, warning=FALSE, message=FALSE}
kable(data.frame(all_pubs %>%
          dplyr::filter(Year == 2021) %>%
            dplyr::select(-Year)), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```

## 2020
```{r, echo = FALSE, warning=FALSE, message=FALSE}
kable(data.frame(all_pubs %>%
          dplyr::filter(Year == 2020) %>%
            dplyr::select(-Year)), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```

## 2019
```{r, echo = FALSE, warning=FALSE, message=FALSE}
kable(data.frame(all_pubs %>%
          dplyr::filter(Year == 2019) %>%
            dplyr::select(-Year)), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```
<br>
  
## 2018
```{r, echo = FALSE, warning=FALSE, message=FALSE}
kable(data.frame(all_pubs %>%
          dplyr::filter(Year == 2018) %>%
            dplyr::select(-Year)), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```
<br>
  
## 2017
```{r, echo = FALSE, warning=FALSE, message=FALSE}
kable(data.frame(all_pubs %>%
          dplyr::filter(Year == 2017) %>%
            dplyr::select(-Year)), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```
<br>
  

## Pre-2017
```{r, echo = FALSE, warning=FALSE, message=FALSE}
kable(data.frame(all_pubs %>%
          dplyr::filter(Year < 2017) %>%
            dplyr::select(-Year)), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```
<br>

## Our top-10 cited papers
```{r, echo = FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.height=3.5, fig.width=5.5}
source('functions/scholar_summary.R')
source('./scholar_ids/scholar_ids.R')
top10 <- scholar_top10(author_list = scholar_ids)
kable(data.frame(top10), row.names = F,
      format = 'html') %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  column_spec(1, width = '30em') %>%
  column_spec(2, italic = T, width = '20em') %>%
  column_spec(3, width = '20em') %>%
  scroll_box(width = "100%", height = "400px")
```

<br>

## Our papers in graphs
```{r, echo = FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.height=3.5, fig.width=5.5}
source('functions/scholar_summary.R')
source('./scholar_ids/scholar_ids.R')
scholar_summary(author_list = scholar_ids)
```

```{r, echo = FALSE, warning=FALSE, message=FALSE, fig.align='center', fig.height=5, fig.width=5.5}
source('functions/scholar_allpubs.R')
source('./scholar_ids/scholar_ids.R')
scholar_topjournals(author_list = scholar_ids)
```


